# Generated by Django 2.0.1 on 2019-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('facebook_id', models.CharField(max_length=128,
                                                 primary_key=True, serialize=False, unique=True)),
                ('pdf_url', models.TextField()),
                ('kerberos', models.CharField(max_length=32, unique=True)),
                ('sided', models.CharField(choices=[
                 ('S', 'SINGLE'), ('D', 'DOUBLE')], max_length=1)),
                ('printer_type', models.CharField(choices=[
                 ('B', 'BLACKWHITE'), ('C', 'COLOR')], max_length=1)),
                ('n_copies', models.IntegerField(default=0)),
            ],
        ),
    ]
