# Generated by Django 2.0.1 on 2019-03-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintUserState',
            fields=[
                ('facebook_id', models.CharField(max_length=128,
                                                 primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('P', 'PDF'), ('K', 'KERBEROS'), (
                    'S', 'SIDED'), ('T', 'PRINTER_TYPE'), ('N', 'N_COPIES')], max_length=1)),
            ],
        ),
    ]
